create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  category varchar(80) not null,
  price numeric(10, 2) not null check (price >= 0),
  quantity integer not null check (quantity >= 0),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "Allow public product reads"
on public.products
for select
using (true);

create policy "Allow public product inserts"
on public.products
for insert
with check (true);

create policy "Allow public product updates"
on public.products
for update
using (true)
with check (true);

create policy "Allow public product deletes"
on public.products
for delete
using (true);
